
import { ClientData } from "./types";

// --- Dummy Providers for demo ---
export const providerList = [
  "Dr. Emily Clark",
  "Dr. Mike Evans",
  "Sarah Johnson, LCSW",
  "James Wright, PsyD",
  "Helen Ray, LMFT",
  "Derek Martinez, MD",
  "Dr. Kara Liu",
  "Logan Myers, LCSW",
  "Alex Chen, MD",
  "Ruby Hall, LMFT",
  "Nicole Ford, PsyD",
  "Julia O'Neil, LPC",
  "Dr. Sylvester Richards",
  "Cheyenne Flores, LCSW",
  "Morgan Rivera, MD"
];

// --- 1. Clients data (Active) ---
export const generateClientsData = (): ClientData[] => {
  return [
    {
      name: "Samuel Grant",
      dateStarted: "Apr 15, 2024",
      provider: providerList[0],
      email: "s.grant@email.com",
      phone: "555-101-1111",
      growthStage: "foundation",
    },
    {
      name: "Linda Monroe",
      dateStarted: "Feb 12, 2024",
      provider: providerList[1],
      email: "l.monroe@email.com",
      phone: "555-222-2323",
      growthStage: "developing",
    },
    {
      name: "Gabriel Lee",
      dateStarted: "Jan 21, 2024",
      provider: providerList[2],
      email: "g.lee@email.com",
      phone: "555-333-4343",
      growthStage: "established",
    },
    {
      name: "Julia Brown",
      dateStarted: "Dec 08, 2023",
      provider: providerList[3],
      email: "j.brown@email.com",
      phone: "555-444-5656",
      growthStage: "foundation",
    },
    {
      name: "Ethan Shaw",
      dateStarted: "Oct 17, 2023",
      provider: providerList[4],
      email: "e.shaw@email.com",
      phone: "555-555-7878",
      growthStage: "established",
    },
    {
      name: "Megan Diaz",
      dateStarted: "Sep 03, 2023",
      provider: providerList[5],
      email: "m.diaz@email.com",
      phone: "555-666-9090",
      growthStage: "developing",
    },
    {
      name: "Randy Pitt",
      dateStarted: "Aug 10, 2023",
      provider: providerList[6],
      email: "randyp@email.com",
      phone: "555-101-9191",
      growthStage: "foundation",
    },
    {
      name: "Aria Bell",
      dateStarted: "Jul 24, 2023",
      provider: providerList[7],
      email: "ariabell@email.com",
      phone: "555-102-2020",
      growthStage: "established",
    },
    {
      name: "Paul Black",
      dateStarted: "Jun 15, 2023",
      provider: providerList[8],
      email: "paulb@email.com",
      phone: "555-333-4440",
      growthStage: "developing",
    },
    {
      name: "Sharon White",
      dateStarted: "May 09, 2023",
      provider: providerList[9],
      email: "sharonw@email.com",
      phone: "555-222-3331",
      growthStage: "foundation",
    },
    {
      name: "Clive Green",
      dateStarted: "Apr 02, 2023",
      provider: providerList[10],
      email: "cliveg@email.com",
      phone: "555-111-1341",
      growthStage: "developing",
    },
    {
      name: "Anna Foster",
      dateStarted: "Mar 17, 2023",
      provider: providerList[11],
      email: "annaf@email.com",
      phone: "555-121-4414",
      growthStage: "established",
    },
    {
      name: "Nikki Page",
      dateStarted: "Feb 01, 2023",
      provider: providerList[12],
      email: "nikkip@email.com",
      phone: "555-313-6611",
      growthStage: "foundation",
    },
    {
      name: "Pat Nielson",
      dateStarted: "Jan 16, 2023",
      provider: providerList[13],
      email: "patn@email.com",
      phone: "555-151-9669",
      growthStage: "established",
    },
    {
      name: "Sidney Kay",
      dateStarted: "Dec 23, 2022",
      provider: providerList[14],
      email: "sidkay@email.com",
      phone: "555-171-7878",
      growthStage: "developing",
    },
  ];
};

// --- 2. Discharged tab data ---
export const generateDischargedData = (): ClientData[] => {
  return [
    {
      name: "Connor Adams",
      dateDischarged: "Apr 05, 2024",
      provider: providerList[2],
      email: "connor.a@email.com",
      phone: "999-333-2222",
      growthStage: "developing",
    },
    {
      name: "Beatrice Cook",
      dateDischarged: "Feb 25, 2024",
      provider: providerList[0],
      email: "beatrice.c@email.com",
      phone: "888-111-2223",
      growthStage: "established",
    },
    {
      name: "Victor Tran",
      dateDischarged: "Jan 11, 2024",
      provider: providerList[5],
      email: "vic.tran@email.com",
      phone: "978-120-9898",
      growthStage: "foundation",
    },
    {
      name: "Amy Rivera",
      dateDischarged: "Mar 22, 2024",
      provider: providerList[6],
      email: "amy.r@email.com",
      phone: "555-808-3300",
      growthStage: "developing",
    },
    {
      name: "Wendy Lee",
      dateDischarged: "May 01, 2024",
      provider: providerList[8],
      email: "wendy.l@email.com",
      phone: "555-707-1212",
      growthStage: "established",
    },
    {
      name: "Felix Webb",
      dateDischarged: "Jun 10, 2024",
      provider: providerList[9],
      email: "felix.w@email.com",
      phone: "555-456-8709",
      growthStage: "foundation",
    },
    {
      name: "April Moss",
      dateDischarged: "Jul 24, 2023",
      provider: providerList[4],
      email: "aprilm@email.com",
      phone: "555-333-0078",
      growthStage: "developing",
    },
    {
      name: "Omar Perez",
      dateDischarged: "Jul 17, 2023",
      provider: providerList[10],
      email: "operez@email.com",
      phone: "555-101-1811",
      growthStage: "established",
    },
    {
      name: "Zara Lane",
      dateDischarged: "Sep 12, 2023",
      provider: providerList[1],
      email: "zaral@email.com",
      phone: "555-661-7477",
      growthStage: "foundation",
    },
    {
      name: "Will Nelson",
      dateDischarged: "Oct 01, 2023",
      provider: providerList[3],
      email: "willn@email.com",
      phone: "555-323-8288",
      growthStage: "developing",
    },
    {
      name: "Nina Bell",
      dateDischarged: "Nov 16, 2023",
      provider: providerList[11],
      email: "ninab@email.com",
      phone: "555-144-3399",
      growthStage: "established",
    },
    {
      name: "Peter Rowe",
      dateDischarged: "Dec 19, 2023",
      provider: providerList[7],
      email: "prow@email.com",
      phone: "555-010-2324",
      growthStage: "foundation",
    },
    {
      name: "Eva Reese",
      dateDischarged: "Jan 15, 2023",
      provider: providerList[13],
      email: "eva@email.com",
      phone: "555-611-9022",
      growthStage: "developing",
    },
    {
      name: "Cody Black",
      dateDischarged: "Feb 11, 2023",
      provider: providerList[14],
      email: "codyb@email.com",
      phone: "555-102-3122",
      growthStage: "established",
    },
    {
      name: "Dina Cooper",
      dateDischarged: "Mar 21, 2023",
      provider: providerList[12],
      email: "dinac@email.com",
      phone: "555-141-8787",
      growthStage: "foundation",
    },
  ];
};

// --- 3. Issues tab data ---
export const generateIssuesData = (): ClientData[] => {
  return [
    {
      name: "Robin Paul",
      dateFlagged: "Mar 13, 2024",
      provider: providerList[1],
      email: "robin.p@email.com",
      phone: "565-331-4441",
      growthStage: "foundation",
    },
    {
      name: "Naomi Chen",
      dateFlagged: "Feb 29, 2024",
      provider: providerList[3],
      email: "naomi.chen@email.com",
      phone: "565-110-8888",
      growthStage: "developing",
    },
    {
      name: "Gary Kim",
      dateFlagged: "Jan 22, 2024",
      provider: providerList[11],
      email: "gkim@email.com",
      phone: "333-444-5555",
      growthStage: "established",
    },
    {
      name: "Stella Kwok",
      dateFlagged: "Jan 06, 2024",
      provider: providerList[13],
      email: "skwok@email.com",
      phone: "858-312-5132",
      growthStage: "foundation",
    },
    {
      name: "Oscar Brooks",
      dateFlagged: "Dec 27, 2023",
      provider: providerList[4],
      email: "obrooks@email.com",
      phone: "222-555-9090",
      growthStage: "established",
    },
    {
      name: "Quincy Vaughn",
      dateFlagged: "Nov 19, 2023",
      provider: providerList[10],
      email: "quincy@email.com",
      phone: "444-777-1112",
      growthStage: "developing",
    },
    {
      name: "Jonas Batu",
      dateFlagged: "Oct 07, 2023",
      provider: providerList[8],
      email: "jonas@email.com",
      phone: "987-333-4111",
      growthStage: "foundation",
    },
    {
      name: "Leslie Pike",
      dateFlagged: "Sep 23, 2023",
      provider: providerList[5],
      email: "leslie@email.com",
      phone: "111-678-1212",
      growthStage: "developing",
    },
    {
      name: "Janet Ivers",
      dateFlagged: "Aug 18, 2023",
      provider: providerList[9],
      email: "janet@email.com",
      phone: "102-304-5677",
      growthStage: "established",
    },
    {
      name: "Amir Castillo",
      dateFlagged: "Jul 02, 2023",
      provider: providerList[2],
      email: "amir@email.com",
      phone: "558-302-1456",
      growthStage: "foundation",
    },
    {
      name: "Kira Bryant",
      dateFlagged: "Jun 23, 2023",
      provider: providerList[12],
      email: "kira@email.com",
      phone: "789-945-3694",
      growthStage: "developing",
    },
    {
      name: "Hunter Nash",
      dateFlagged: "May 12, 2023",
      provider: providerList[14],
      email: "hnash@email.com",
      phone: "703-491-8921",
      growthStage: "established",
    },
    {
      name: "Ben Cooper",
      dateFlagged: "Apr 24, 2023",
      provider: providerList[7],
      email: "bcoop@email.com",
      phone: "123-456-7890",
      growthStage: "foundation",
    },
    {
      name: "Christa Hall",
      dateFlagged: "Mar 31, 2023",
      provider: providerList[0],
      email: "christah@email.com",
      phone: "753-357-2222",
      growthStage: "developing",
    },
    {
      name: "Miles Parker",
      dateFlagged: "Feb 18, 2023",
      provider: providerList[6],
      email: "mparker@email.com",
      phone: "444-888-1414",
      growthStage: "established",
    },
  ];
};
