// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zihgewzxoeozgfhyczhf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InppaGdld3p4b2VvemdmaHljemhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyNDQyNjMsImV4cCI6MjA3MTgyMDI2M30.cAfo0zn6M7dJIsN4Zou6kdAph_RbVwvFR4z6Kwh9uJs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});